# -*- coding: utf-8 -*-
"""
Created on Mon Mar 19 08:46:22 2018

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

@author: Nasdap
"""

#fibonacci generated
def get_fibonacci_list(limit):
    result = [1,2]
    while result[len(result)-1] + result[len(result)-2] <= limit:
        result.append(result[len(result)-1] + result[len(result)-2])
    return(result)
    
get_fibonacci_list(100)

def get_even_only(some_list):
    result = [x for x in some_list if x%2 == 0]
    return(result)

get_even_only([1,2,3,4,5,6])

problem_limit = 4*10**6
answer_02 = sum(get_even_only(get_fibonacci_list(problem_limit)))
answer_02 
